services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8079:8080"

  frontsrv:
    build: 
      context: ./WepPartDeliveryProject/WepPartDeliveryProject/client_app
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000' # Port used for the http protocol.
    environment:
      - SSL_CERT_FILE=/bundle/localhost.cer
      - NEXT_PUBLIC_HOME_API=https://host.docker.internal:8081
      - NODE_TLS_REJECT_UNAUTHORIZED="0"
    volumes: 
      - "./WepPartDeliveryProject/WepPartDeliveryProject/client_app/.env:/app/.env"
      - "./WepPartDeliveryProject/certs/localhost.cer:/bundle/localhost.cer"

  deliverysrv:
    build: 
      context: ./WepPartDeliveryProject
      dockerfile: ./WepPartDeliveryProject/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      SSL_CERT_FILE: /bundle/localhost.pfx

      KafkaSettings__BootstrapServers: c0008.corp.ekassir.com:9092
      KafkaSettings__GroupId: test_group_id
      KafkaSettings__ContainerEventsTopic: ContainerEvents

      AllowedHosts: "*"

      Neo4jSettings__Neo4jConnection: bolt://c0008.corp.ekassir.com:7687
      Neo4jSettings__Neo4jUser: neo4j
      Neo4jSettings__Neo4jPassword: 123456sa
      Neo4jSettings__Neo4jDatabase: neo4j

      ApplicationSettings__CountOfItemsOnWebPage: 8
      ApplicationSettings__JwtSecretKey: 1super_security_key11super_security_key11super_security_key11super_security_key11super_security_key11super_security_key1
      ApplicationSettings__GenerateData: false

      ClientAppSettings__ClientAppApi: https://f69b-185-97-201-110.ngrok-free.app
      ClientAppSettings__PathToPublicSourceDirecroty: e:\\Programs\\DeliveryServices\\WepPartDeliveryProject\\WepPartDeliveryProject\\client_app\\public\\
      ClientAppSettings__DirectoryWithDishImages: dishes

      JsonSerializer: System.Text
      ASPNETCORE_ENVIRONMENT: Development
      ServiceName: otel-test
      UseTracingExporter: otlp
      UseMetricsExporter: otlp
      HistogramAggregation: explicit

      Otlp__Endpoint: http://c0008.corp.ekassir.com:4317

      AspNetCoreInstrumentation__RecordException: true

      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0,1
      OTEL_METRIC_EXPORT_INTERVAL: 60000
      OTEL_METRIC_EXPORT_TIMEOUT: 30000

    ports:
      - '8080:8080' # Port used for the http protocol.
      - '8081:8081' # Port used for the https protocol.
    volumes: 
      - "./WepPartDeliveryProject/WepPartDeliveryProject/appsettings.json:/app/appsettings.json"
      - "./WepPartDeliveryProject/WepPartDeliveryProject/client_app/public/:/app/client_app/public/"
      - "./WepPartDeliveryProject/certs/localhost.pfx:/app/localhost.pfx"

  orderworker:
    build: 
      context: ./WepPartDeliveryProject
      dockerfile: ./OrderWorker/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      SSL_CERT_FILE: /bundle/localhost.pfx

      KafkaSettings__BootstrapServers: c0008.corp.ekassir.com:9092
      KafkaSettings__GroupId: order_group_id
      KafkaSettings__ContainerEventsTopic: ContainerEvents
      KafkaSettings__ContainerOrdersTopic: ContainerOrders

      AllowedHosts: "*"

      Neo4jSettings__Neo4jConnection: bolt://c0008.corp.ekassir.com:7687
      Neo4jSettings__Neo4jUser: neo4j
      Neo4jSettings__Neo4jPassword: 123456sa
      Neo4jSettings__Neo4jDatabase: neo4j

      JsonSerializer: System.Text
      ASPNETCORE_ENVIRONMENT: Development
      ServiceName: orderworker
      UseTracingExporter: otlp
      UseMetricsExporter: otlp
      HistogramAggregation: explicit

      Otlp__Endpoint: http://c0008.corp.ekassir.com:4317

      AspNetCoreInstrumentation__RecordException: true

      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0,1
      OTEL_METRIC_EXPORT_INTERVAL: 60000
      OTEL_METRIC_EXPORT_TIMEOUT: 30000

    ports:
      - '8080:8080' # Port used for the http protocol.
      - '8081:8081' # Port used for the https protocol.
    volumes: 
      - "./WepPartDeliveryProject/WepPartDeliveryProject/appsettings.json:/app/appsettings.json"
      - "./WepPartDeliveryProject/WepPartDeliveryProject/client_app/public/:/app/client_app/public/"
      - "./WepPartDeliveryProject/certs/localhost.pfx:/app/localhost.pfx"

  authservice:
    build: 
      context: ./WepPartDeliveryProject
      dockerfile: ./AuthService/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      SSL_CERT_FILE: /bundle/localhost.pfx

      AllowedHosts: "*"

      Neo4jSettings__Neo4jConnection: bolt://c0008.corp.ekassir.com:7687
      Neo4jSettings__Neo4jUser: neo4j
      Neo4jSettings__Neo4jPassword: 123456sa
      Neo4jSettings__Neo4jDatabase: neo4j

      ApplicationSettings__JwtSecretKey: 1super_security_key11super_security_key11super_security_key11super_security_key11super_security_key11super_security_key1

      JsonSerializer: System.Text
      ASPNETCORE_ENVIRONMENT: Development
      ServiceName: orderworker
      UseTracingExporter: otlp
      UseMetricsExporter: otlp
      HistogramAggregation: explicit

      Otlp__Endpoint: http://c0008.corp.ekassir.com:4317

      AspNetCoreInstrumentation__RecordException: true

      OTEL_TRACES_SAMPLER: parentbased_traceidratio
      OTEL_TRACES_SAMPLER_ARG: 0,1
      OTEL_METRIC_EXPORT_INTERVAL: 60000
      OTEL_METRIC_EXPORT_TIMEOUT: 30000

  neo4j:
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=123456sa
    ports:
      - '7474:7474' # Port used for the http protocol.
      - '7473:7473' # Port used for the https protocol.
      - '7687:7687' # Port used for the bolt protocol.
    volumes:
      - neo4j_data:/bitnami/neo4j/data

volumes:
  neo4j_data:
  zookeeper_data: