services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8079:8080"

  frontsrv:
    build: 
      context: ./WepPartDeliveryProject/WepPartDeliveryProject/client_app
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000' # Port used for the http protocol.
    environment:
      - SSL_CERT_FILE=/bundle/localhost.cer
      - NEXT_PUBLIC_HOME_API=https://host.docker.internal:8081
      - NODE_TLS_REJECT_UNAUTHORIZED="0"
    volumes: 
      - "./WepPartDeliveryProject/WepPartDeliveryProject/client_app/.env:/app/.env"
      - "./WepPartDeliveryProject/certs/localhost.cer:/bundle/localhost.cer"

  deliverysrv:
    build: 
      context: ./WepPartDeliveryProject
      dockerfile: ./WepPartDeliveryProject/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      SSL_CERT_FILE: /bundle/localhost.pfx
    ports:
      - '8080:8080' # Port used for the http protocol.
      - '8081:8081' # Port used for the https protocol.
    volumes: 
      - "./WepPartDeliveryProject/WepPartDeliveryProject/appsettings.json:/app/appsettings.json"
      - "./WepPartDeliveryProject/WepPartDeliveryProject/client_app/public/:/app/client_app/public/"
      - "./WepPartDeliveryProject/certs/localhost.pfx:/bundle/localhost.pfx"
      - "./WepPartDeliveryProject/certs/localhost.pfx:/app/localhost.pfx"

  neo4j:
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=123456sa
    ports:
      - '7474:7474' # Port used for the http protocol.
      - '7473:7473' # Port used for the https protocol.
      - '7687:7687' # Port used for the bolt protocol.
    volumes:
      - neo4j_data:/bitnami/neo4j/data

volumes:
  neo4j_data:
  zookeeper_data: