import Head from 'next/head'
import { FC } from "react"
import styles from '@/styles/Home.module.css'
import DishedList from '@/components/DishedList'
import ClientLayout from '@/components/ClientLayout'
import { GetStaticProps } from 'next'

const dishClientCard = {
  images: ["/суши1.png","/суши.png","/суши1.png","/суши.png"],
  name: "Калифорния",
  description: "Классический ролл с лососем, «снежным крабом»,кунжутным майонезом, авокадо и огурцом,панированный в икре тобико",
  price : 389,
  id: 1,
}

const dishClientCard1 = {
  images: ["/суши.png","/суши1.png","/суши.png","/суши1.png"],
  name: "Филадельфия",
  description: "Нежный ролл с лососем,сливочным сыром и огурцом",
  price : 549,
  id: 2,
}

export const getStaticProps:GetStaticProps = async () =>{
  const resp = await fetch(`https://localhost:7161/main/getCategoriesList`);
  const data = await resp.json() as categoryItem[];

  return {
    props:{
      categories: data
    }
  }
}

const Home: FC<{categories:Array<categoryItem>}> = ({categories}) => {
  return (
    <ClientLayout categories={categories}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <DishedList {...{dishes: [dishClientCard, dishClientCard1]}}/>
        </div>
      </main>
    </ClientLayout>
  )
}

export default Home;