import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import DishCard from '@/components/cards/DishCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{backgroundColor:"grey"}}>
          <DishCard imagePath="/суши.png"/>
          <DishCard imagePath="/суши1.png"/>
        </div>
      </main>
    </>
  )
}
