import Head from 'next/head'
import { FC } from "react"
import styles from '@/styles/Home.module.css'
import DishedList from '@/components/DishedList'
import ClientLayout from '@/components/ClientLayout'
import { GetStaticPaths, GetStaticProps } from 'next'

export const getStaticPaths:GetStaticPaths = async () => {
    const resp = await fetch(`https://localhost:7161/main/getCategoriesList`);
    const categories = await resp.json() as categoryItem[];
    const paths = categories.map((value)=> ({params: {category: value.linkName}}))

  return {
    paths,
    fallback: false, // can also be true or 'blocking'
  }
}

export const getStaticProps:GetStaticProps = async (context) => {
    const category = context.params?.category;
    const resp1 = await fetch(`https://localhost:7161/main/getCategoriesList`);
    const categoryList = await resp1.json() as categoryItem[];

    const resp2 = await fetch(`https://localhost:7161/main/getDishesList/${category}`);
    const dishList = await resp2.json() as dishClientCardProps[];

    return {
        props:{
            categories: categoryList,
            dishes: dishList,
        }
    }
}

type categoryPageProps = {
  categories:categoryItem[], 
  dishes: dishClientCardProps[],
}

const Category: FC<categoryPageProps> = ({categories, dishes}) => {
  return (
    <ClientLayout categories={categories}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
            <DishedList {...{dishes, page: 1}}/>
        </div>
      </main>
    </ClientLayout>
  )
}

export default Category;